# Generated by Django 4.2.7 on 2023-11-29 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEncuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 11, 29, 0, 6, 30, 665967)),
        ),
    ]
