# Generated by Django 4.2.7 on 2023-12-09 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEncuesta', '0002_alter_opinion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 20, 54, 19, 781532)),
        ),
    ]
