# Generated by Django 4.2.7 on 2023-12-10 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppEncuesta', '0004_alter_opinion_fecha_respuestaalternativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaalternativa',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 15, 12, 47, 343803)),
        ),
    ]
