# Generated by Django 4.2.7 on 2023-12-10 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppEncuesta', '0005_respuestaalternativa_id_usuario_alter_opinion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 17, 3, 38, 480604)),
        ),
        migrations.AlterField(
            model_name='respuestaalternativa',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEncuesta.usuario'),
        ),
    ]
