# Generated by Django 4.2.7 on 2023-12-10 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEncuesta', '0006_alter_opinion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 17, 4, 18, 244628)),
        ),
    ]
